apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    httpMethod: POST
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
    basicAuth: false
