global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: '${PROMETHEUS_CLUSTER_NAME:-gotel-local}'
    environment: '${ENVIRONMENT:-development}'
    
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Remote write configuration (for federating to external Prometheus)
remote_write:
  # Uncomment to enable remote write to external Prometheus
  # - url: '${PROMETHEUS_REMOTE_WRITE_URL:-}'
  #   basic_auth:
  #     username: '${PROMETHEUS_REMOTE_WRITE_USER:-}'
  #     password: '${PROMETHEUS_REMOTE_WRITE_PASSWORD:-}'
  #   queue_config:
  #     max_samples_per_send: 1000
  #     max_shards: 200
  #     capacity: 2500

scrape_configs:
  # Scrape Prometheus own metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  # Scrape GoTel application metrics (if running externally)
  - job_name: 'gotel'
    static_configs:
      - targets: ['${GOTEL_SCRAPE_TARGET:-host.docker.internal:8080}']
    scrape_interval: 5s
    metrics_path: /metrics
    honor_labels: true
