global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: '${PROMETHEUS_CLUSTER_NAME:-gotel-local}'
    environment: '${ENVIRONMENT:-development}'
    
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Scrape Prometheus own metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  # Scrape OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 15s
    metrics_path: /metrics

  # Scrape metrics exported by OTEL Collector Prometheus exporter
  - job_name: 'otel-collector-gotel'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 5s
    metrics_path: /metrics
    honor_labels: true

  # Scrape GoTel application metrics (if running externally with native Prometheus exporter)
  - job_name: 'gotel-app'
    static_configs:
      - targets: ['${SCRAPE_TARGET:-host.docker.internal:8080}']
    scrape_interval: 5s
    metrics_path: /metrics
    honor_labels: true
